services:
    react:
        container_name: nextjs-test-react
        image: will871/node:dev
        volumes:
            - .:/var/www/app
        ports:
            - 8080:8080
            - 3000:3000
        tty: true
